name: Run Hello-world from py script
on: push

jobs:
    Hello:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v2
                with:
                    python-version: '3.10'

            - name: Run Python script
              run: python3 hello.py