name: Testing_Schedule
on:
    schedule:
      - cron: '* * * * *'
  
jobs:
    cron-job:
        runs-on: ubuntu-latest

        steps:
        - name: checkout code
          uses: action/checkout@v2

        - name: setup-python
          uses: action/setup-python@v2
          
          with:
                python-version: '3.13'

        - name: Run-python
          run: python hello.py